language: ruby

rvm:
  - 2.3

addons:
  apt:
    packages:
    - chromium-browser
    # TODO: Use chromedriver from apt once it's been updated to v2.31+.
    # - chromium-chromedriver

# For now, download chromedriver directly:
before_script:
  - >
      wget -q https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip &&
      unzip chromedriver_linux64.zip

cache:
  bundler: true
  directories:
  # Cache the Onebox data and views to speed up tests
  - tmp/cache/onebox-data
  - tmp/cache/onebox-views
  - spec/dummy/tmp/cache/onebox-data
  - spec/dummy/tmp/cache/onebox-views

bundler_args: --path ../../vendor/bundle --without debug
gemfile:
  - spec/gemfiles/rails_4_2.gemfile
  - spec/gemfiles/rails_5_0.gemfile
  - spec/gemfiles/rails_5_1.gemfile
  - spec/gemfiles/rails_5_2.gemfile

env:
  matrix:
  # Username and password from http://docs.travis-ci.com/user/database-setup/
  - DB=sqlite3
  - DB=mysql2     DB_USERNAME=root     DB_PASSWORD=""
  - DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
  global:
  - COVERAGE=1
  - TRAVIS=1
  - CHROMEDRIVER_PATH=$PWD/chromedriver

# Avoid rake here, as the RSpec test task spawns a new process which does not run via bundler.
script:
- bundle exec rspec --force-color --format d --tag=~js
- bundle exec rspec --force-color --format d --tag=js
- bundle exec rubocop
- bundle exec codeclimate-test-reporter
- MIGRATION_SPEC=1 bundle exec rspec spec/migration --force-color --format d

notifications:
  slack:
    secure: bnoj7Q/2yA3gtJ2IR/YtXrWCGvN7ukHKnhg1oNYJsOYNk0oEMMgjmGnIRrcdxO4peyOid6aKlcMmP7zrOzPEJsN3qAA4UUCRGq0TgZ2RDMX1sRZ8NN/xCyt84WU9aEtTF0V1hUyG/OaQ7G65XN/XuwJGzw6VDSZE54FSdR/5/eQ=

dist: trusty
sudo: required
